birth_year=input("what is your birth date?")
age= 2024 - int(birth_year)
print(age)
name=input("What is your name?")
print(len(name))
surname =input("What is your surname?")
print(f"{name}" f"{surname}")